// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdateUser struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	ProfilePicture string `json:"ProfilePicture"`
}

type NewEducation struct {
	UserID       string  `json:"UserID"`
	School       string  `json:"School"`
	Degree       string  `json:"Degree"`
	FieldOfStudy string  `json:"FieldOfStudy"`
	StartDate    string  `json:"StartDate"`
	EndDate      string  `json:"EndDate"`
	Grade        float64 `json:"Grade"`
	Activites    string  `json:"Activites"`
	Description  string  `json:"Description"`
}

type NewExperience struct {
	UserID         string `json:"UserID"`
	Title          string `json:"Title"`
	EmploymentType string `json:"EmploymentType"`
	CompanyName    string `json:"CompanyName"`
	Location       string `json:"Location"`
	Active         bool   `json:"Active"`
	StartYear      string `json:"StartYear"`
	EndYear        string `json:"EndYear"`
	Industry       string `json:"Industry"`
	Description    string `json:"Description"`
}
